# Generated by Django 3.0.3 on 2022-02-25 03:21

import app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('notes', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('notes', models.TextField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=17, validators=[app.models.PhoneValidator])),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Organization')),
            ],
        ),
    ]
