# Generated by Django 3.0.3 on 2022-02-12 03:06

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20220212_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='phone',
            field=models.CharField(blank=True, max_length=17, validators=[app.models.PhoneValidator]),
        ),
    ]
